name: Java CI with Gradle

on:
  push:
    branches: [ mainline ]
  pull_request:
    branches: [ mainline ]

jobs:
  job_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 8.0.192, 11.0.x, 11.0.3, 12, 13 ]
    name: Java ${{ matrix.java }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Clean
      run: gradle clean
    - name: Unit test
      run: gradle test
    - name: Build
      run: gradle build
  
  job_windows:
    runs-on: windows-latest
    strategy:
      matrix:
        java: [ 8, 8.0.192, 11.0.x, 11.0.3, 12, 13 ]
    name: Java ${{ matrix.java }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Clean
      run: gradle clean
    - name: Unit test
      run: gradle test
    - name: Build
      run: gradle build

  job_mac:
    runs-on: macos-latest
    strategy:
      matrix:
        java: [ 8, 8.0.192, 11.0.x, 11.0.3, 12, 13 ]
    name: Java ${{ matrix.java }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Clean
      run: gradle clean
    - name: Unit test
      run: gradle test
    - name: Build
      run: gradle build
